### ISSUE TITLE
Update bootstrap package to install Salt 2015.5.5

### ISSUE THREAD

**Issue by uvsmtid** [uvsmtid/common-salt-states#11]
At the moment `salt-minion-2014.7.1-1.el7.noarch` already causes problems on CentOS 5 for `common.tmux` state which would otherwise execute cleanly on `salt-minion-2015.5.5-1.el7.noarch`.

```
----------
          ID: deploy_tmux_resurrect_plugin
    Function: archive.extracted
        Name: /opt
      Result: False
     Comment: 
     Started: 16:53:33.675349
    Duration: 9.463 ms
     Changes:   
              ----------
              pid:
                  6441
              retcode:
                  2
              stderr:
                  tar: This does not look like a tar archive
                  tar: --: Not found in archive
                  tar: -s: Not found in archive
                  tar: -t: Not found in archive
                  tar: -r: Not found in archive
                  tar: -i: Not found in archive
                  tar: -p: Not found in archive
                  tar: --: Not found in archive
                  tar: -c: Not found in archive
                  tar: -o: Not found in archive
                  tar: -m: Not found in archive
                  tar: -p: Not found in archive
                  tar: -o: Not found in archive
                  tar: -n: Not found in archive
                  tar: -e: Not found in archive
                  tar: -n: Not found in archive
                  tar: -t: Not found in archive
                  tar: -s: Not found in archive
                  tar: -=: Not found in archive
                  tar: -1: Not found in archive
                  tar: -f: Not found in archive
                  tar: '/var/cache/salt/minion/files/base/_opt_tmux-resurrect.tar': Not found in archive
                  tar: Exiting with failure status due to previous errors
              stdout:

```
